### ISSUE TITLE
Add readme to @restatedev/restate and @restatedev/restate-server

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#1068]
Minor improvement: Add readme to https://www.npmjs.com/package/@restatedev/restate and https://www.npmjs.com/package/@restatedev/restate-server.

**Comment by tillrohrmann** [comment]
cc @jackkleeman maybe you know how this is done easily.

**Comment by jackkleeman** [comment]
@tillrohrmann its simply whatever we copy in as README.md https://github.com/restatedev/restate/blob/main/.github/workflows/npm.yml#L77

**Comment by tillrohrmann** [comment]
> @tillrohrmann its simply whatever we copy in as README.md https://github.com/restatedev/restate/blob/main/.github/workflows/npm.yml#L77

Cool :-) Can we put something in there because it looks so empty on npmjs.com.

**Comment by tillrohrmann** [comment]
Nice, we are uploading the repos Readme now. This is a good start.
