### ISSUE TITLE
Deduplicate restate_ingress_grpc::reflection::v1 and ::v1alpha

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#1192]
With https://github.com/restatedev/restate/pull/1183, we introduced duplicate modules restate_ingress_grpc::reflection::v1 and ::v1alpha. The two modules contain almost identical code. The only difference is in the types they are using. It would be good to deduplicate them.

**Comment by slinkydeveloper** [comment]
Irrelevant now
