### ISSUE TITLE
[Design] Ingress API to provide separate start/fetch invocation

### ISSUE THREAD

**Issue by AhmedSoliman** [restatedev/restate#1257]
In addition to supporting blocking sync calls on ingress, I propose we transparently generate APIs for service methods where the user can start the invocation and get an invocation ID immediately, then another API call to fetch/attach to an inflight invocation given this ID.

**Comment by slinkydeveloper** [comment]
This feature pretty much exists now, so I'm tempted to close this:

* The user by providing the idempotency id will store and keep around invocation results, plus won't re-execute the invocation twice
* The /send feature allows to send a request without waiting for the response
* The /attach and /output feature provide a way to retrieve the result
