### ISSUE TITLE
gRPC reflection not working with gRPC-based TS services

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#1262]
A user reported that invoking gRPC-based TS services via grpcurl fails [1]. The problem seems to be that the TS SDK does not ship the correct file descriptors for `google/protobuf/descriptor.proto` and `dev/restate/ext.proto`. Since we are currently removing the gRPC specific parts from the SDK, I suggest to add a temporary band-aide that patches the respective files on the server side.

What is a bit unclear is whether other file descriptors are affected by the same problem.

The fix will only applied to the `release-0.8` branch.

[1] https://discord.com/channels/1128210118216007792/1214469975163801661/1214469975163801661

**Comment by slinkydeveloper** [comment]
Can we close this?

**Comment by tillrohrmann** [comment]
The problem has been fixed in the `release-0.8` via https://github.com/restatedev/restate/commit/1d34beed1d894794bbd7e97733662352b04055cf.
