### ISSUE TITLE
Split runtime logging from service logging

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#1310]
Right now, the server mixes internal traces with traces belonging to service invocations (which it generates on behalf of the service invocations). This mixes two concerns: Server tracing and logical invocation tracing. Ideally, we could split them by emitting them to two different endpoints or under two different contexts. That way we can improve our server tracing which will become helpful for debugging a distributed Restate server.

**Comment by tillrohrmann** [comment]
@muhamadazmy this issue is completed, right?

**Comment by muhamadazmy** [comment]
Yes, it is. Sorry I should have closed it
