### ISSUE TITLE
Stabilize configuration

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#1314]
Server configuration is a high-traffic structure that we use everyday, we want to make sure that it's easy for us to use, evolve, and that it's easy for users to understand and work with. The proposal is:
- Use toml as the primary format (optionally, we can support YAML and/or JSON)
- Max nesting is of tables is 3 levels only, (e.g. `[bifrost.providers.local]`), flatter-config is easier to navigate, better if less than 3.
- Group common top-level options into a single structure `CommonOptions`
- Allow _some_ of the top-level options to be controllable from the command line, i.e.`restate --bind-address 0.0.0.0:5555 --node-name=my-hode`
- A dedicated section per role (or major component)
  - `admin`
  - `worker`
  - `cluster_controller`
  - `bifrost`
  - `metadata_store`

Additionally, introduce common convention for naming (all enums are snake_case, common prefixes, etc.)

**Comment by AhmedSoliman** [comment]
We now support toml only.

**Comment by tillrohrmann** [comment]
@AhmedSoliman are there bigger pending tasks for the stabilization of the configuration for the launch?

**Comment by AhmedSoliman** [comment]
I don’t think so. We can close.
