### ISSUE TITLE
Revisit and improve error messages

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#1344]
Currently, we have a couple of overly generic error messages that we display to our users. We should revisit them and check whether we can provide more meaningful information for solving an erroneous situation.

Also make sure that we don't say that this is a bug if it is not clear (e.g. some invariant is broken, panic, etc.).

```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/restate/issues/1345
```

**Comment by slinkydeveloper** [comment]
I'm gonna close this as the only subtask is open. Reopen single issues if we need to reconsider other error messages.
