### ISSUE TITLE
Expose timers table

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/restate#1444]

**Comment by slinkydeveloper** [comment]
What do you think about this @tillrohrmann ?

**Comment by tillrohrmann** [comment]
Would this enable a new feature we want to implement or would it be mainly for better observability?

**Comment by slinkydeveloper** [comment]
> would it be mainly for better observability?

Better observability.

**Comment by slinkydeveloper** [comment]
I don't think this is relevant anymore because the primary reason to do this was to look at the scheduled invocations.
