### ISSUE TITLE
Bug with configuration change dir and signing key loading

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/restate#1471]
Just create a key and put it in whatever directory (e.g. in the root of the git repo):

```
$ stat a.pem
  File: a.pem
  Size: 119             Blocks: 8          IO Block: 4096   regular file
Device: 0,39    Inode: 56131187    Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/slinkydeveloper)   Gid: ( 1000/slinkydeveloper)
Context: unconfined_u:object_r:container_file_t:s0:c188,c1021
Access: 2024-04-26 09:57:36.473206050 +0200
Modify: 2024-04-26 09:56:29.101350915 +0200
Change: 2024-04-26 09:57:36.442206105 +0200
 Birth: 2024-04-26 09:57:36.441206107 +0200
```

And try to load it:

```
RESTATE_REQUEST_IDENTITY_PRIVATE_KEY_PEM_FILE=a.pem cargo run --bin restate-server
```

Loading will fail with:

```
 Restate application failed
    error: building cluster controller failed: failed building the service client: Failed to read request identity private key: No such file or directory (os error 2)
    restate.error.code: None
```

This seems related to the fact that we change directory during bootstrap time. I just tried to add a log statement in `SigningKey::from_pem_file` printing cwd and file name, and got

```
2024-04-26T08:16:04.211825Z INFO restate_service_client::request_identity::v1
  Loading
    request_identity_private_key_pem_file: "a.pem"
    cwd: "/home/slinkydeveloper/projects/work/restate/restate-data/fedora"
```

While the file is in `/home/slinkydeveloper/projects/work/restate/a.pem`.

**Comment by slinkydeveloper** [comment]
cc @AhmedSoliman @jackkleeman

**Comment by jackkleeman** [comment]
So, I guess we need to provide an absolute path until this is resolved?

**Comment by slinkydeveloper** [comment]
> So, I guess we need to provide an absolute path until this is resolved?

As I workaround I guess so, could we fix this though? It's quite unexpected :)

**Comment by AhmedSoliman** [comment]
I'll remove the chdir shortly anyway.

**Comment by AhmedSoliman** [comment]
Should be fixed by https://github.com/restatedev/restate/pull/1473
