### ISSUE TITLE
Invoker treats 503 as protocol violation

### ISSUE THREAD

**Issue by AhmedSoliman** [restatedev/restate#1548]
It sounds like we should handle 503 Service Unavailable better when invoking handlers. Load balancers and http2 reverse proxies will return 503 when one of the upstream servers are not available, we do retry those errors but we treat them as "Protocol violation errors":
```
2024-05-22T17:29:58.950323Z WARN restate_invoker_impl
  Error when executing the invocation, retrying in 60ms 513us 328ns.
    error: [RT0012] unexpected http status code: 503 Service Unavailable. For more details, look at the docs with https://docs.restate.dev/references/errors#RT0012
    restate.error.code: RT0012
    restate.invocation.id: inv_1l8n0Bsg2WP3148oHDZoSjX3wKROc36YU1
    restate.invocation.target: Counter/my-counter/get
RT0012

Protocol violation error. This can be caused by an incompatible runtime and SDK version. If the error persists, please file a [bug
report](https://github.com/restatedev/restate/issues).
```

This should be a normal retryable error instead.

**Comment by edude03** [comment]
How do you imagine this being solved @AhmedSoliman? I see there are a bunch of things [mapped to the RT0012 error code](https://github.com/restatedev/restate/blob/1e5d334190e77175b37c44bc6646942f80d56e49/crates/invoker-impl/src/invocation_task/mod.rs#L92) which triggers the incompatible message. I don't see an existing "General Invocation" Error, so I assume we'd need to add a new RT00xx and enum variation for it? Then presumably change the [response handler](https://github.com/restatedev/restate/blob/4988f8a46139df82a6cee41a6eba6b2f2a2cc07a/crates/invoker-impl/src/invocation_task/service_protocol_runner.rs#L420) to special case 503s? (and maybe other codes)

**Comment by tillrohrmann** [comment]
@edude03, I think we need to introduce handling returned status codes differently [here](https://github.com/restatedev/restate/blob/be27b02e7b4adfeaafe6ef37f5a516d031064b57/crates/invoker-impl/src/invocation_task/service_protocol_runner.rs#L416). We could use RT0010 instead for 503 status codes.
