### ISSUE TITLE
Investigate Kafka subscription ingestion performance

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#1610]
Stephan noticed that our ingestion rate from Kafka (100 req/s) is significantly lower than our processing speed of invocations (1000 req/s once buffered). This could be caused by some inefficiencies on the Kafka ingestion path or the Kafka consumer itself. We should investigate where the bottleneck is and whether we can do something about it.

**Comment by tillrohrmann** [comment]
Could be caused by https://github.com/tokio-rs/tokio/issues/4730?

**Comment by slinkydeveloper** [comment]
Closing this, some investigation was done, and this discussion shows what else can be done https://github.com/restatedev/restate/pull/1964
