### ISSUE TITLE
Make workflow retention time configurable

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#1624]
Make workflow retention time configurable. Right now it is hard coded to 24 h. See https://github.com/restatedev/restate/blob/c7306c53a26805d0fcc783182d50a08d42a92a6c/crates/schema-api/src/invocation_target.rs#L20.

**Comment by slinkydeveloper** [comment]
This should be already configurable https://github.com/restatedev/restate/blob/main/crates/admin-rest-model/src/services.rs#L60

**Comment by tillrohrmann** [comment]
I guess what is not configurable is the default value, right? Like if you want to configure a different retention time for all your workflows.

**Comment by slinkydeveloper** [comment]
The default can't be configured you're right. So far we didn't have a case for this.

**Comment by tillrohrmann** [comment]
I guess it wouldn't hurt/be hard to expose it. I guess the case could be if have a different requirement for all your workflows and you don't want to manually change them one by one.
