### ISSUE TITLE
Failing to bind to a port should cause restate to exit

### ISSUE THREAD

**Issue by igalshilman** [restatedev/restate#1669]
It seems like if the ingress port 8080 is currently bound to some other process, restate won't complain about this.
Can be also relevant for other ports as well.
We should at least print a warning, even better to fail fast.

context: https://discord.com/channels/1128210118216007792/1255835235761917992

**Comment by tillrohrmann** [comment]
I've tried reproducing this problem locally but was not able to do so, so far. The code also states that we are always trying to bind to a specific address before starting a server. If the bind operation fails, then the Restate server is stopped. This happens for the admin server, http ingress, node server and metadata server in my env.

I will try to clarify with the user reporting the problem.

**Comment by tillrohrmann** [comment]
Apparently, the problem arose when using VSCode's port forwarding feature. So it might actually be unrelated to Restate.

**Comment by tillrohrmann** [comment]
> Maybe last question here, do we happen to bind on all interfaces? (`0.0.0.0`)?

Yes, by default we do unless users configure the address differently.
