### ISSUE TITLE
SDK Rust

### ISSUE THREAD

**Issue by yerke** [restatedev/restate#1676]
Hello. 

On your website I see only references to JS and Java/Kotlin SDKs. Do you have plans to add Rust SDK as well?

Thanks.

**Comment by tillrohrmann** [comment]
Hi @yerke, at the moment Restate supports TS, Java and Kotlin. We are planning to expand the set of supported languages very soon. Your interest in the Rust SDK is noted. Once I can give you a reliable timeline, I'll share it with you.

**Comment by crrow** [comment]
I'm also interested in Rust SDK. And I'm wiling to help out, any associated issue that I can help?

**Comment by slinkydeveloper** [comment]
Hey all, we have released our first version of the Rust SDK! https://crates.io/crates/restate-sdk/

We're looking for feedback!
