### ISSUE TITLE
`TerminalError` / `TerminalException` could output with more details in the cli

### ISSUE THREAD

**Issue by djang0dev** [restatedev/restate#1712]
Hi 👋, first thanks for your work on restate and what's coming!

Might be an idea to output a `TerminalError` with the status `completed` and with `Error` / `Caused by` and even the `Trace ID` ?

Cause atm, there's no UI diff between a successful completed inv / an inv that has been terminated with a `TerminalError`

e.g with this simple workflow:
```ts
export const throwableWorkflow = workflow({
  name: "throwable",
  handlers: {
    run: async (ctx: WorkflowContext) => {
      throw new TerminalError("Should show up in the restate cli?", { errorCode: 500 })
    },
  },
})
```
![CleanShot 2024-07-10 at 15 25 31@2x](https://github.com/restatedev/restate/assets/71573572/aee7a012-a94e-43c7-9ff3-ef49aafaf922)

Thanks!

**Comment by slinkydeveloper** [comment]
Hey @djang0dev you should now be able to see whether workflows completed with success or failure, and failure reason, from the next restate release! This will require you to update the runtime too.
