### ISSUE TITLE
Make channel settings configurable in net_utils.rs

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#1766]
It would be great to make the channel settings configurable here: https://github.com/restatedev/restate/blob/8ea75044bb4b4504b685c302b1336fbc0d6f8d72/crates/core/src/network/net_util.rs#L45.

**Comment by aradwann** [comment]
this is resolved via https://github.com/restatedev/restate/pull/2193?

**Comment by tillrohrmann** [comment]
Yes, it is. Thanks for the pointer @aradwann 🙏
