### ISSUE TITLE
Service endpoint using HTTP 1.1 with TLS

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/restate#1899]
HTTP 1.1 doesn't work with TLS/ALPN.

**Comment by slinkydeveloper** [comment]
Right now we're unnecessarily enforcing HTTP versions on discovery, setting either HTTP 1.1 or HTTP 2. This is not needed for HTTPs, so I propose to change the behavior as follows:

* For HTTPs, let ALPN do its job, and save in the discovered metadata whether the response was HTTP 1.1 or HTTP 2
* For HTTP, use h2c by default, and let the user override with HTTP 1.1

**Comment by tillrohrmann** [comment]
Linking the original PR which introduced the current version https://github.com/restatedev/restate/pull/1232 and pulling in @jackkleeman for input.

**Comment by tillrohrmann** [comment]
Thanks for reporting this issue @slinkydeveloper. Why is HTTP 1.1 not working with TLS/ALPN at the moment? I thought the discovery part works as you've described the intended state. Or are you referring to the actual invocation request from the invoker?

**Comment by slinkydeveloper** [comment]
Because of this line of code here: https://github.com/restatedev/restate/pull/1900/files#diff-2722962a539bfff537d32f9ef19e3c76b76e09919bda67b1d745593bfc55b4afR68

**Comment by tillrohrmann** [comment]
So w/o explicitly enabling the HTTP client to use HTTP1.1 via `enable_http1`, it would not work with HTTP1.1?
