### ISSUE TITLE
Improve replicated loglet configuration building

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#2031]
The Nodeset selector should given a `ReplicationProperty`, alive set of log server nodes and an optionally preferred node calculate a nodeset which fulfills the `ReplicationProperty`. To include the preferred node in the resulting nodeset will allow to colocate the sequencer on this node (e.g. if the partition processor leader is running there). There are situations where we cannot create a nodeset given the set of alive log servers. The nodeset selector should also respect the `StorageState::is_writable()`.

**Comment by tillrohrmann** [comment]
The returned nodeset must never fall below the minimum nodeset size. So if the minimum nodeset size is `3` and we have three available nodes in the cluster, then we cannot create a different nodeset once one node dies.

**Comment by pcholakov** [comment]
https://github.com/restatedev/restate/pull/2099 contains a first stab at automatically reconfiguring the loglets while respecting the existing replication requirement. The major unaddressed requirement there is how to let the operator define this requirement initially.
