### ISSUE TITLE
Clean up CLI output for Ingress data types / content types

### ISSUE THREAD

**Issue by StephanEwen** [restatedev/restate#2101]
Currently, when registering a new service, the output for handlers looks like this:
```
     HANDLER        INPUT                                                        OUTPUT
     snapshot       one of ["none", "value of content-type 'application/json'"]  value of content-type 'application/json'
```

I would suggest to simplify it to this:
```
     HANDLER        INPUT                OUTPUT
     snapshot       "application/json"   "application/json"
```

Technically, this ignores the detail that "none" is also accepted as a special case, but I believe that isn't necessary to add here and the win in simplicity/clarity is worth it.

**Comment by slinkydeveloper** [comment]
the problem of ignoring to print _none_ is that it can get confusing if you have an handler defined without any input (e.g. https://github.com/restatedev/sdk-typescript/blob/3e5138e9c909eebc484f7f05c85c2b7e435b3691/packages/restate-sdk-examples/src/example.ts#L50), and now suddendly you register it and you see `application/json`. Would it be good to maybe just shortening this to simply _none or "application/json"_?

**Comment by StephanEwen** [comment]
I think the current state is more confusing, I took me a while until I connected the dots that "none" means "parameter skipped".
To me, this is one of the cases where "technically less correct" might actually be more helpful.
