### ISSUE TITLE
Awaiting a durable promise is not showing up in the CLI / journal 

### ISSUE THREAD

**Issue by StephanEwen** [restatedev/restate#2102]
When the below code is awaiting the promise (third `await` statement), the journal view in the CLI will look as in the figure below.

```typescript
async function run(ctx: WorkflowContext) => {
  await ctx.run(() => someAction());
  await ctx.sleep(1000);
  await ctx.promise<boolean>("approved");
  // .. continue
}
```

![image](https://github.com/user-attachments/assets/d286eb92-9d77-4485-8572-c073b2d0b956)

The journal misses to show that the promise is being awaited.

**Comment by slinkydeveloper** [comment]
We can add this, it's pretty straightforward, although in the current journal we don't record where the user actually awaits for the promise, so this might not represent the real point where you await it. E.g. this code:

```
let myPromise = ctx.promise<boolean>("approved");
await ctx.sleep(1000);
await myPromise;
await ctx.run("someAction", () => someAction());
```

Will show as:

```
Promise("approved")
Sleep(1000)
Run("someAction")
```

**Comment by StephanEwen** [comment]
Makes sense. I wonder if there is a case to be made for "info messages" in the journal, that don't represent a persistent step per se, but just an info step, such as "awaiting promise".

Or maybe this is something to attach to the "suspend" message, what was the awaited point.

Regardless of how we implement this, the info what is being awaited is super critical for debugging/observability.

**Comment by slinkydeveloper** [comment]
I just figured that i implemented this already :D, we just haven't released this yet https://github.com/restatedev/restate/pull/1919
