### ISSUE TITLE
Avoid blocking in the PartitionProcessorManager when being in the control loop

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#2146]
One concrete seems to be the spawning of new `PartitionProcessors` which takes a noticeable amount of time. Even with the release build, it takes roughly ~ 150ms for a single `PartitionProcessor` to get spawned. A way to solve this problem is to make the spawning of new `PartitionProcessors` asynchronous.

**Comment by muhamadazmy** [comment]
I improved the tracing a little bit for the starting of the partition processors to be able to get this view 
it seems most of the delay is basically waiting on the metadata version. I will add more tracing information to be sure

![image](https://github.com/user-attachments/assets/1d5d5e2e-b662-46d4-b136-560685543383)

**Comment by tillrohrmann** [comment]
I think this can be explained by the default `metadata_update_interval` (https://github.com/restatedev/restate/blob/a09bcc8f17df729aecf1b31236ac5076f18dc2a0/crates/core/src/metadata/manager.rs#L289). I assume that we have fetched the `Logs` before and now we are awaiting for the next tick to fetch the new `PartitionTable`.

When I ran some tests on my machine I noticed that https://github.com/restatedev/restate/blob/819f4086f50ea8cf57bf4274913b7126503161cc/crates/worker/src/partition_processor_manager.rs#L720 took roughly 150ms to complete. This could be an artifact of MacOS.

**Comment by muhamadazmy** [comment]
@tillrohrmann can you try my fix on your mac and see if it improves the startup time for you?
