### ISSUE TITLE
Enable Restate runtime to trace across processes

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#2155]
Having solved #1310, we can now implement proper tracing for the runtime. As a first step, we could check what's the current state to see what we need to add to support tracing of Restate runtime calls across processes (e.g. a Bifrost appender sending requests to a remote sequencer which sends a wave of store requests to a set of `LogServers`). Figuring out which information our network messages need to transport to support this will help us avoiding protocol changes later on.

**Comment by muhamadazmy** [comment]
I have been investigating this issue and we probably going to follow the https://www.w3.org/TR/trace-context/ standard and inject the `traceparent` and `tracestate` headers in the Message Header. 

To avoid possible protocol changes in the future a `SpanContext` structure can be introduced and added to the `Message.Header` the `SpanContext` can then be defined as a Map (which is not supported by protobuf) hence we can use a repeated (keyValuePair) objects. This will allow us to extend the SpanContext with extra non-standard headers if needed.

The final message will look something like
```
message {
  header {
    msg_id = 1,
    versions ...
    ...
    span_context {
       (traceparent, "trace parent value"),
       (tracestate, "trace state value")
    }
  }
}
```
