### ISSUE TITLE
Passthrough of headers from external client to service

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/restate#23]
Allow external clients to pass headers to service endpoints.

**Comment by slinkydeveloper** [comment]
# API Proposal

## Method in context

Naively I would say that the context should have a method like:

```
ctx.headers() -> Map<String, String>
```

Or multimap if we want to support it:

```
ctx.headers() -> Map<String, List<String>>
```

## Java gRPC

If we want to play nice with `Interceptor`s & co. perhaps we should make sure we fill the `Metadata` object when creating the server, such that interceptors can access them: https://github.com/grpc/grpc-java/blob/master/examples/src/main/java/io/grpc/examples/header/HeaderServerInterceptor.java#L44

As far as I understand there's no way, once you're in the service method, to access directly the `Metadata`. Everything you wanna pass through needs to be propagated in the `Context` through interceptors: https://stackoverflow.com/questions/40112374/how-do-i-access-request-metadata-for-a-java-grpc-service-i-am-defining

So in general I would say for the Java SDK we should have both support for the metadata in the interceptors and the method `ctx.headers()`

## API Proposal (TS gRPC)

As far as I can see the library we use now in sdk-typescript has no support for interceptors, not headers, in the code generation, so there's nothing we need to integrate with. Just `ctx.headers()` should be enough.

**Comment by slinkydeveloper** [comment]
About the list of headers to passthrough, I guess we can start with passing everything except a blacklist of headers that can be misinterpreted:

* `content-type` and `accept` -> These are interpreted by restate.
* The caching related headers? http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header -> we might have a feature that interprets those (e.g. if we have response caching)
* The idempotency key header -> This is interpreted by restate. If we wanna pass this through let's have them in the 
* `Host` -> This could leak information about the ingress and load balancer, which the service shouldn't be aware of?
* w3c trace context -> that we already process it internally, and we already give to SDKs

Is there some other header that can be misunderstood/can cause issues we should blacklist?

I guess we can always change this list.

**Comment by tillrohrmann** [comment]
@jackkleeman would Jason need this feature?

**Comment by jackkleeman** [comment]
@tillrohrmann i dont believe so, he is going to be using an edge http server between restate and clients anyway so he has total control over the api surface
