### ISSUE TITLE
Run examples as part of the release process

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#474]
We currently have a couple of examples (https://github.com/restatedev/example-lambda-ts-greeter, https://github.com/restatedev/example-ticket-reservation-system, https://github.com/restatedev/example-shopping-cart-typescript) for which we create releases. As part of the release process we could try to run the examples (e.g. have a Terraform script that deploys the example to AWS lambda).

**Comment by slinkydeveloper** [comment]
Solved
