### ISSUE TITLE
Status inspection

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#505]
Based on #294 we could track which invocations are in a problematic state (retry loop) (e.g. after having been retried for a number of attempts, having seen a specific error (SDK bug), etc.). Exposing the set of problematic invocations to the user could allow her to investigate potential problems and to manually intervene.

```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/restate/issues/517
- [ ] https://github.com/restatedev/restate/issues/621
- [ ] https://github.com/restatedev/restate/issues/622
```

**Comment by slinkydeveloper** [comment]
This is now irrelevant, and it has been fixed by CLI and exposing more invocation state info
