### ISSUE TITLE
Inject observability-focused headers in req/res from ingress

### ISSUE THREAD

**Issue by AhmedSoliman** [restatedev/restate#896]
Introduce header enrichment by ingress for external requests and service-to-service invocations that populate information like:
- `RequestId`: A unique value propagated back to the user that can be used in debugging a certain request
- `Retries`: The number of retries attempted for this invocation

Subject to more ideas...

**Comment by slinkydeveloper** [comment]
Not sure there's anything to do here, as we expose invocation id all around in logs (runtime and sdk), tracing, etc, and we use W3C trace context too and propagate it both from ingress and through service-to-service.

If you wanna do e2e tracing, just set the w3c trace context header in the request you send to the ingress.
If you want to know how many retries have been made, you can use the CLI/SQL interface to investigate that.

I'm gonna close it, reopen if you think this is not solved yet.
