### ISSUE TITLE
Implement Admin API endpoint to send the cancel command

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/restate#918]
Implement the Admin API command to send the cancel command to the partition processor https://github.com/restatedev/restate/issues/914

See https://docs.google.com/document/d/14s7D6KP1IKNS1K3OrVbZNKGNei9TO_-9Sk0YC5mpht8/edit#heading=h.wgh520sqrw51

For the time being we don't need this command to wait for the compensation to end.

**Comment by tillrohrmann** [comment]
Subsumed by https://github.com/restatedev/restate/issues/996
