### ISSUE TITLE
Meta rejects/fails endpoint discovery that removes an RPC method

### ISSUE THREAD

**Issue by AhmedSoliman** [restatedev/restate#930]
While testing the new discover CLI command. I was removing a method `unreserve` and adding `trySomethingNew`  in `TicketDb` (from our `examples/`) and trying to discover the app with a new endpoint. The server ended up rejecting it (not using `--force`) thinking that I've changed the service instance type, but I didn't!

Also related issues:
* [http semantics] If this is a user input or logical error we shouldn't return http 500.
* [Improvement] Best if the error message can tell the user what was the previous and new instance types that it failed to match.
* 
<img width="1258" alt="Screenshot 2023-11-30 at 18 09 18" src="https://github.com/restatedev/restate/assets/59670/ffd53fe8-2ece-4ad5-85de-13064fb109b8">

**Comment by tillrohrmann** [comment]
@slinkydeveloper do you know why this is happening?

**Comment by slinkydeveloper** [comment]
@tillrohrmann https://github.com/restatedev/restate/pull/879#discussion_r1412106491

**Comment by tillrohrmann** [comment]
> @tillrohrmann [#879 (comment)](https://github.com/restatedev/restate/pull/879#discussion_r1412106491)

Thanks for the update. Does it make sense to take this PR over and drive it over the finishing line?
