### ISSUE TITLE
Flip `✔ Are you sure you want to apply those changes? ` default to yes when change is safe

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/restate#959]
Just tried to register a service, on a blank restate, and the change was completely safe, since it just added services. 

When i got asked  `✔ Are you sure you want to apply those changes? ` it defaulted to `no`, rather than yes

Would it be ok to flip the default in the "safe cases" no to yes?

**Comment by AhmedSoliman** [comment]
Humans are animals of habits. Changing the default based on the situation confuses the automatic brain response when seeing those messages. I don't think we should pursue this approach.
