### ISSUE TITLE
Allow a subscription to set a batch size and time interval

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#974]
A user requested the following feature: Allow a subscription to set a batch size and time interval. The time interval used to poll Kafka and the buffer size the max number of records to send in one message to the subscribing service. This will make the service more efficient than one at a time messaging.

[1] https://discord.com/channels/1128210118216007792/1136316066696532069/1183605557190459574

**Comment by slinkydeveloper** [comment]
Nothing to do here I think. The user can set all the librdkafka options they want already.
