### ISSUE TITLE
Store caller information for background invokes

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#997]
In order to also display for background invokes who was the caller, we should track this information in the runtime. I propose to not rely on the `ResponseSink` for extracting the caller information but to have a dedicated field for it.

**Comment by slinkydeveloper** [comment]
> I propose to not rely on the ResponseSink for extracting the caller information but to have a dedicated field for it.

@tillrohrmann can you elaborate on why relying on response sink was not considered an option here?

**Comment by tillrohrmann** [comment]
Because for background calls the response sink would be `None`.

**Comment by slinkydeveloper** [comment]
Uh sorry i completely forgot that!
